config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :daily_changes
  root to: "home#welcome"
end

app/models/daily_change.rb
class DailyChange < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  has_many :daily_changes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/daily_changes_controller.rb
class DailyChangesController < ApplicationController

  before_filter :set_user

  def index

  end

  def show
  end

  def new
    @daily_change = DailyChange.new
  end

  def create
    # @daily_change = DailyChange.create(daily_change_params)
    binding.pry
    render text: params.inspect
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private
  def set_user
    @user = current_user
  end

  def daily_change_params
    params.require(:daily_change).permit(:value, :date)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!
  before_filter :set_user

  def welcome

  end

  private
  def set_user
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/daily_changes/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <%= form_for @daily_change do |f| %>

        <div class="form-group">
          <%= f.label :value %>
          <%= f.number_field :value, step: 'any', class: 'form-control' %>
        </div>

        <div class="form-group">
        <%= f.label :date %>
        <%= f.date_field :date, value: Date.today, class: 'form-control' %>
        </div>

        <%= f.submit class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/daily_changes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>new daily change</h1>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/home/welcome.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h1>welcome <%= @user.first_name %></h1>

      <%= button_to "Add New Daily Change", new_daily_change_path, method: 'get', class: "btn btn-default"  %>
      <%= button_to "Sign out", destroy_user_session_path, method: 'delete', class: "btn btn-default" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SidsMoneyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>